name: ofxstatement-bkb
on:
  push:
    branches: master
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync --dev

    - name: Test with pytest
      run: |
        pipenv run pytest -v

    - name: Check with mypy
      run: |
        pipenv run mypy src

    - name: Check with black
      run: |
        pipenv run black --check setup.py src

